// Copyright 2020 Itts Mee. All rights reserved.
// Use of this source code is governed by a license
// that can be found in the LICENSE file.

// THIS FILE HAS BEEN GENERATED BY l10n using l10n.json.
// ON 2020-11-04 11:24:15.189564975 +0100 CET . DO NOT EDIT.
// CHANGES WILL DISAPPEAR AFTER NEXT RUN OF l10n.

/*
 l10n_generated.go contains all localized strings and
 functions for translating (L10nTranslate),
 replacing text/template variables (L10nReplace),
 and a conveniance function for localizing errors (L10nLocalizeError)
*/

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"strings"
	"text/template"

	. "github.com/hwheinzen/stringl10n/mistake"
)

// Type l10nPair is used during string localization.
type l10nPair struct {
	Lang  string
	Value string
}

// l10nMap contains all key strings and all translations.
var l10nMap = make(map[string][]l10nPair, 10)

// L10nTranslate returns a translation of a given text
// according to the chosen language code.
func L10nTranslate(key, lang string) (out string, err error) {
	fnc := "L10nTranslate"

	pairs, ok := l10nMap[key]
	if !ok {
		err := Err{
			Fix: "EXAMPLE:no entry for '{{.Name}}'",
			Var: []struct {
				Name  string
				Value interface{}
			}{
				{"Name", key},
			},
		}
		return "", fmt.Errorf(fnc+":%w", err)
	}
	for _, v := range pairs {
		if len(lang) >= 5 { // assuming POSIX locales: language + country
			if v.Lang == lang[:5] {
				return v.Value, nil
			}
		}
	}
	for _, v := range pairs {
		if len(lang) >= 2 { // assuming POSIX locales: language only
			if v.Lang == lang[:2] {
				return v.Value, nil
			}
		}
	}

	err = Err{
		Fix: "EXAMPLE:no {{.Nam2}} translation for '{{.Name}}'",
		Var: []struct {
			Name  string
			Value interface{}
		}{
			{"Name", key},
			{"Nam2", lang},
		},
	}
	return "", fmt.Errorf(fnc+":%w", err)
}

// l10nVars declares all possible variables needed for substitution.
type l10nVars struct {
	Info string
}

// L10nReplace replaces text/template expressions and returns
// the changed text string. Variables in these text/template
// expressions are substituted by values.
func L10nReplace(tmpl string, vars []struct {
	Name  string
	Value interface{}
}) (txt string, err error) {
	fnc := "L10nReplace"

	t := template.New("t")
	_, err = t.Parse(tmpl)
	if err != nil {
		e := Err{
			Fix: "EXAMPLE:error parsing '{{.Name}}'",
			Var: []struct {
				Name  string
				Value interface{}
			}{
				{"Name", tmpl},
			},
		}
		return "", fmt.Errorf(fnc+":%w:"+err.Error(), e)
	}

	allVars := l10nVars{}

	for _, pair := range vars {
		switch pair.Name {
		case "Info":
			v, ok := pair.Value.(string)
			if !ok {
				e := Err{
					Fix: "EXAMPLE:wrong variable type {{.Type}} for '{{.Name}}', expected: {{.Nam2}}",
					Var: []struct {
						Name  string
						Value interface{}
					}{
						{"Type", fmt.Sprintf("%T", pair.Value)},
						{"Name", tmpl},
						{"Nam2", "string"},
					},
				}
				return "", fmt.Errorf(fnc+":%w:"+err.Error(), e)
			}
			allVars.Info = v
		default:
			err = Err{
				Fix: "EXAMPLE:variable {{.Name}} not declared",
				Var: []struct {
					Name  string
					Value interface{}
				}{
					{"Name", pair.Name},
				},
			}
			return "", fmt.Errorf(fnc+":%w", err)
		}
	}

	var b bytes.Buffer
	err = t.Execute(&b, allVars)
	if err != nil {
		e := Err{
			Fix: "EXAMPLE:error executing template {{.Name}}",
			Var: []struct {
				Name  string
				Value interface{}
			}{
				{"Name", tmpl},
			},
		}
		return "", fmt.Errorf(fnc+":%w:"+err.Error(), e)
	}

	return b.String(), nil
}

// L10nLocalizeError takes the innermost wrapped error of in and tries
// to translate the error message and then tries to replace text/template
// expressions with variable values if available. It creates a new error
// and returns it wrapped with the input error message as prefix.
func L10nLocalizeError(in error, lang string) (out, err error) {
	fnc := "L10nLocalizeError"

	// Unwrap
	var inner, e error
	var ss []string
	for inner, e = in, errors.Unwrap(in); e != nil; inner, e = e, errors.Unwrap(e) {
		ss = append(ss, strings.Replace(inner.Error(), e.Error(), "%w", 1))
	}
	ss = append(ss, inner.Error())

	// Translate
	txt, err := L10nTranslate(inner.Error(), lang)
	if err != nil {
		return nil, fmt.Errorf(fnc+":%w", err)
	}

	// Substitute
	type varser interface {
		Vars() []struct {
			Name  string
			Value interface{}
		}
	}
	f, ok := inner.(varser)
	if ok {
		txt, err = L10nReplace(txt, f.Vars())
		if err != nil {
			return nil, fmt.Errorf(fnc+":%w", err)
		}
		out = Err{
			Fix: txt,
			Var: f.Vars(),
		}
	} else {
		out = Err{Fix: txt}
	}

	// Wrap again
	for i := len(ss) - 1; i != 0; i-- {
		out = fmt.Errorf(ss[i-1], out)
	}

	return out, nil
}

// init fills the translation map.
func init() {
	fnc := "init"

	var l10nJSON = `{
 "EXAMPLE:complex error with '{{.Info}}'": [
  {
   "Lang": "en",
   "Value": "complex error with '{{.Info}}'"
  },
  {
   "Lang": "de",
   "Value": "komplizierter Fehler mit '{{.Info}}'"
  }
 ],
 "EXAMPLE:simple error": [
  {
   "Lang": "en",
   "Value": "simple error"
  },
  {
   "Lang": "de",
   "Value": "einfacher Fehler"
  }
 ]
}`

	err := json.Unmarshal([]byte(l10nJSON), &l10nMap)
	if err != nil {
		e := Err{Fix: "L10N:error unmarshaling 'l10nJSON'"}
		log.Fatalln(fnc+":%w:"+err.Error(), e)
	}
	l10nJSON = "" // no longer needed
}

// THIS FILE HAS BEEN GENERATED.
// DO NOT EDIT.
// CHANGES WILL DISAPPEAR AFTER NEXT RUN OF go generate.
