// Copyright 2015 Hans-Werner Heinzen. All rights reserved.
// Use of this source code is governed by a license
// that can be found in the LICENSE file.

package main

var code = `// Copyright {{.Copyright}}. All rights reserved.
// Use of this source code is governed by a license
// that can be found in the LICENSE file.

// THIS FILE HAS BEEN GENERATED BY {{.Generator}}.
// DO NOT EDIT.
// CHANGES WILL DISAPPEAR AFTER NEXT RUN OF {{.Generator}}.

/*
 {{.GenFile}} contains all localized strings and
 functions for translating (l10nTranslate)
 and substituting variables (l10nSubstitute).
*/

package {{.Package}}

import (
	"bytes"
	"encoding/json"
	"log"
	"text/template" {{if ne (len .Funcs) 0}}{{range .Funcs}}{{if ne .Path ""}}
	"{{.Path}}"{{end}}{{end}}{{end}}
)

// Type l10nPair is used during string localization.
type l10nPair struct {
	Lang  string
	Value string
}

// l10nMap contains all key strings and all translations.
var l10nMap = make(map[string][]l10nPair, 10)

// l10nTrans returns a translation of a given text
// according to the chosen language code.
// Errors are logged.
func l10nTrans(key, lang string) (value string) {
	fncname := "l10nTrans"

	pairs, ok := l10nMap[key]
	if !ok {
		log.Print(fncname+": no entry for key: ", key)
		return key
	}
	for _, v := range pairs {
		if v.Lang == lang {
			return v.Value
		}
	}
	//log.Print("l10nTrans: language: ", lang, " not defined for key: ", key)
	return key
}

// l10nVars declares all variables needed for substitution.
type l10nVars struct { {{range .Vars}}
	{{.Name}} {{.Type}}{{end}}
}

// Varser interface has a method that returns
// Name-string/Value-interface{} pairs.
type Varser interface {
	Vars() []struct{ // Vars returns Name-Value-Pairs
		Name string
		Value interface{}
	}
}

// l10nSubst resolves text/template expressions and returns
// the changed text string. Variables in these text/template 
// expressions are substituted by values.
// Errors are logged.
func l10nSubst(tmpl string, pairs Varser) (out string) {
	fncname := "l10nSubst"

	t := template.New("tmpl"){{if eq (len .Funcs) 0}}
	_, err := t.Parse(tmpl){{else}}
	funcMap := template.FuncMap { {{range .Funcs}}
		"{{.Name}}": {{.Function}},{{end}}
	}
	_, err := t.Funcs(funcMap).Parse(tmpl){{end}}
	if err != nil {
		log.Print(err)
	}

	all := l10nVars{}

	for _, pair := range pairs.Vars() {
		switch pair.Name { {{range .Vars}}
		case "{{.Name}}":
			tmp, ok := pair.Value.({{.Type}})
			if !ok {
				log.Printf(fncname+": false type for variable {{.Name}}, expected: {{.Type}}, got: %T\n", pair.Value)
				break
			}
			all.{{.Name}} = tmp{{end}}
		default:
			log.Printf(fncname+": variable %s not declared\n", pair.Name)			
		}
	}

	var buf bytes.Buffer
	err = t.Execute(&buf, all) // &buf is an io.Writer
	if err != nil {
		log.Print(err)
	}
	out = buf.String()

	return
}

// init fills the translation map.
func init() {
	err := json.Unmarshal([]byte(l10nJSON), &l10nMap)
	if err != nil {
		log.Fatalln(err)
	}
	l10nJSON = "" // no longer needed
}

var l10nJSON = `
