// Copyright 2020-21 Hans-Werner Heinzen. All rights reserved.
// Use of this source code is governed by a license
// that can be found in the LICENSE file.

package main

var code = `// Copyright {{.Copyright}}. All rights reserved.
// Use of this source code is governed by a license
// that can be found in the LICENSE file.

// THIS FILE HAS BEEN GENERATED BY {{.Generator}} using {{.Input}}.
// ON {{.Generated}}. DO NOT EDIT.
// CHANGES WILL DISAPPEAR AFTER NEXT RUN OF {{.Generator}}.

/*
 {{.GenFile}} contains all localized strings and
 functions for translating (L10nTranslate),
 replacing text/template variables (L10nReplace),
 and a conveniance function for localizing errors (L10nLocalizeError)
*/

package {{.Package}}

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"strings"
	"text/template" {{if ne (len .Funcs) 0}}{{range .Funcs}}{{if ne .Path ""}}
	"{{.Path}}"{{end}}{{end}}{{end}}{{if ne (len .Vars) 0}}{{range .Vars}}{{if ne .Path ""}}
	"{{.Path}}"{{end}}{{end}}{{end}}

	. "github.com/hwheinzen/stringl10n/mistake"
)

// Type l10nPair is used during string localization.
type l10nPair struct {
	Lang  string
	Value string
}

// l10nMap contains all key strings with all their translations.
var l10nMap = make(map[string][]l10nPair, 10)

// L10nTranslate returns the adequate translation of a given text
// according to the chosen language code or an error.
func L10nTranslate(key, lang string) (string, error) {
	fnc := "L10nTranslate"

	if key == "" {
		err := errors.New("L10N:key missing")
		return "", fmt.Errorf(fnc+":%w", err)
	}
	if lang == "" {
		err := errors.New("L10N:lang missing")
		return "", fmt.Errorf(fnc+":%w", err)
	}
	
	pairs, ok := l10nMap[key]
	if !ok {
		err := errors.New("L10N:no entry for '"+key+"'")
		return "", fmt.Errorf(fnc+":%w", err)
	}
	for _, v := range pairs {
		if len(lang) >= 5 { // assuming POSIX locales: language + country
			if v.Lang == lang[:5] {
				return v.Value, nil // found
			}
		}
	}
	for _, v := range pairs {
		if len(lang) >= 2 { // assuming POSIX locales: language only
			if v.Lang == lang[:2] {
				return v.Value, nil // found
			}
		}
	}

	err := errors.New("L10N:no "+lang+" translation for '"+key+"'")
	return "", fmt.Errorf(fnc+":%w", err)
}

// l10nVars declares all variables possibly needed for substitution.
type l10nVars struct { {{range .Vars}}
	{{.Name}} {{.Type}}{{end}}
}

// L10nReplace replaces text/template expressions and returns
// the changed text string. Variables in these text/template 
// expressions are substituted by values or an error.
func L10nReplace(tmpl string, vars []struct {
	Name string
	Value interface{}
}) (string, error) {
	fnc := "L10nReplace"

	if tmpl == "" {
		err := errors.New("L10N:tmpl missing")
		return "", fmt.Errorf(fnc+":%w", err)
	}

	t := template.New("t"){{if eq (len .Funcs) 0}}
	_, err := t.Parse(tmpl){{else}}
	funcMap := template.FuncMap { {{range .Funcs}}
		"{{.Name}}": {{.Function}},{{end}}
	}
	_, err := t.Funcs(funcMap).Parse(tmpl){{end}}
	if err != nil {
		e := errors.New("L10N:error parsing template:\n'"+tmpl+"'\n")
		return "", fmt.Errorf(fnc+":%w:"+err.Error(), e)
	}

	allVars := l10nVars{}

{{$TypeTemplate := .TypeTemplate}}
{{$NameTemplate := .NameTemplate}}
{{$Nam2Template := .Nam2Template}}

	for _, pair := range vars {
		switch pair.Name { {{range .Vars}}
		case "{{.Name}}":
			v, ok := pair.Value.({{.Type}})
			if !ok {
				err = errors.New("L10N:variable '{{.Name}}' should have type {{.Type}} but has "+fmt.Sprintf("%T", pair.Value)+" in template:\n'"+tmpl+"'\n")
				return "", fmt.Errorf(fnc+":%w:", err)
			}
			allVars.{{.Name}} = v{{end}}
		default:
			err = errors.New("L10N:variable '"+pair.Name+"' not declared for template:\n'"+tmpl+"'\n")
			return "", fmt.Errorf(fnc+":%w", err)
		}
	}

	var b bytes.Buffer
	err = t.Execute(&b, allVars)
	if err != nil {
		e := errors.New("L10N:error executing template:\n'"+tmpl+"'\n")
		return "", fmt.Errorf(fnc+":%w:"+err.Error(), e)
	}

	return b.String(), nil
}

// L10nLocalizeError takes the innermost wrapped error of in and tries
// 1. to translate the error message and
// 2. to replace text/template expressions with variable values if available.
// It creates a new error and returns it wrapped again.
//
// If 1. fails it returns two nil errors indicating "NOTFOUND".
// If 2. fails it return nil as out and an error.
func L10nLocalizeError(in error, lang string) (out, err error) {
	fnc := "L10nLocalizeError"

	if in == nil {
		err := errors.New("L10N:in missing")
		return nil, fmt.Errorf(fnc+":%w", err)
	}
	if lang == "" {
		err := errors.New("L10N:lang missing")
		return nil, fmt.Errorf(fnc+":%w", err)
	}

	// Unwrap
	var inner, e error
	var ss []string
	for inner, e = in, errors.Unwrap(in); e != nil; inner, e = e, errors.Unwrap(e) {
		ss = append(ss, strings.Replace(inner.Error(), e.Error(), "%w", 1))
	}
	ss = append(ss, inner.Error())

	// Translate
	txt, err := L10nTranslate(inner.Error(), lang)
	if err != nil {
		return nil, nil // notfound, ignore why
	}

	// Substitute
	type varser interface {
		Vars() []struct {
			Name string
			Value interface{}
		}
	}
	f, ok := inner.(varser)
	if ok {
		txt, err = L10nReplace(txt, f.Vars())
		if err != nil {
			return nil, fmt.Errorf(fnc+":%w", err)
		}
		out = Err{
			Fix: txt,
			Var: f.Vars(),
		}
	} else {
		out = Err{Fix: txt}
	}

	// Wrap again
	for i := len(ss) - 1; i != 0; i-- {
		out = fmt.Errorf(ss[i-1], out)
	}

	return out, nil
}`
